In [9]:
import pandas as pd

# Replace the path with the actual path to where you've saved the CSV file
file_path = '/Users/colleenjung/Desktop/UChicago/Fall ADSP 31012_DataEngineering/Crimes2001toPresent20231106.csv'
crimes_df = pd.read_csv(file_path)

print(crimes_df)

EmptyDataError: No columns to parse from file

In [15]:
crimes= crimes_df
print(crimes.columns)

Index(['ID', 'Case Number', 'Date', 'Block', 'IUCR', 'Primary Type',
       'Description', 'Location Description', 'Arrest', 'Domestic', 'Beat',
       'District', 'Ward', 'Community Area', 'FBI Code', 'X Coordinate',
       'Y Coordinate', 'Year', 'Updated On', 'Latitude', 'Longitude',
       'Location'],
      dtype='object')

In [16]:
# Assuming you've loaded your dataframe as `crimes_df`
# Convert date columns to datetime
crimes_df['Date'] = pd.to_datetime(crimes_df['Date'])

# Generate 'quarter' column from 'Date'
crimes_df['quarter'] = crimes_df['Date'].dt.quarter

# Suppose you want to create a 'neighborhood' dataframe
# This would be more complex and depend on how you can map crimes to neighborhoods
# For example, if you have a mapping, you could do something like:
neighborhoods = pd.DataFrame({
    'neighborhood_id': range(1, len(crimes_df['Block'].unique()) + 1),
    'neighborhood': crimes_df['Block'].unique()
})

# Assume you have a way to calculate 'avg_crime_score' for neighborhoods
# neighborhoods['avg_crime_score'] = ...

# Normalize data for 'crime' table
crimes_normalized = crimes_df[['ID', 'quarter']].copy()
# You would need to join or map the 'neighborhood_id' from the neighborhoods dataframe
# crimes_normalized['neighborhood_id'] = ...

# And so on for each table/entity you need to create

In [17]:
neighborhoods

       neighborhood_id          neighborhood
0                    1     0000X W WACKER DR
1                    2  023XX N LOCKWOOD AVE
2                    3   055XX S ROCKWELL ST
3                    4    045XX N ALBANY AVE
4                    5   087XX S SANGAMON ST
...                ...                   ...
63405            63406     013XX W George St
63406            63407       004XX W Surf St
63407            63408    012XX W Montana St
63408            63409     037XX S Union Ave
63409            63410  014XX N Sandburg TER

[63410 rows x 2 columns]

In [18]:
crimes_normalized

               ID  quarter
0        11037294        1
1        11646293        4
2        11645836        2
3        11645959        4
4        11645601        2
...           ...      ...
7928743  12131776        3
7928744  12082414        2
7928745  12118237        3
7928746  12142591        3
7928747  12002171        1

[7928748 rows x 2 columns]

In [30]:
import pandas as pd

# Re-loading the data after environment reset
community_areas_df = pd.read_csv('/Users/colleenjung/Desktop/UChicago/Fall ADSP 31012_DataEngineering/chicagocommunityareas.csv')

transposed_df = community_areas_df.T


transposed_df.reset_index(inplace=True)

# Now, rename the columns to 'community_area' and 'name'
transposed_df.columns = ['community_area', 'name']

transposed_df = transposed_df[1:]

# Save the transposed data to a new CSV file
transposed_df.to_csv('/Users/colleenjung/Desktop/UChicago/Fall ADSP 31012_DataEngineering/chicago_community_areas_transposed.csv', index=False)

transposed_df.head()

  community_area            name
1              1     Rogers Park
2              2      West Ridge
3              3          Uptown
4              4  Lincoln Square
5              5    North Center

OSError: Cannot save file into a non-existent directory: '/mnt/data'